# @package eval.popqa.metrics.forget_Q_A_ROUGE
defaults:
  - ../../data/datasets@datasets: PopQA_rare_forget #TOFU_QA_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  
  # ^ get default dataset and generation config information

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.popqa.batch_size}

datasets: # override as needed
  PopQA_rare_forget:
    args:
      hf_args:
        path: "SwetieePawsss/UNLamb"
        split: ${eval.popqa.forget_split} #_perturbed
      question_key: ${eval.popqa.question_key}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left