# @package eval.popqa.metrics.retain_Q_A_ROUGE
defaults:
  - ../../data/datasets@datasets: PopQA_rare_retain
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  
  # ^ get default dataset and generation config information

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.popqa.batch_size}
datasets: # override as needed
  TOFU_QA_retain_eval:
    args:
      question_key: ${eval.popqa.question_key}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left