handler: FinetuneTrainer
args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 16
  learning_rate: 2e-4
  bf16: True
  bf16_full_eval: True
  logging_steps: 1
  output_dir: ${paths.output_dir}
  logging_dir: ${trainer.args.output_dir}/logs
  report_to: tensorboard #tensorboard wandb
  ddp_find_unused_parameters: None
  gradient_checkpointing: False
  optim: paged_adamw_8bit #paged_adamw_32bit
  save_strategy: 'no'
  save_only_model: True
  weight_decay: 0.08
  do_train: True
  do_eval: True
  eval_on_start: True
  eval_strategy: 'no' #epoch
  num_train_epochs: 2
  seed: 0
  # embedding_learning_rate: 0.00003
  lr_scheduler_type: cosine