# @package eval.tripunlamb.metrics.forget_Q_A_ROUGE
defaults:
  - ../../data/datasets@datasets: tripunlamb_rare_forget #TOFU_QA_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.tripunlamb.batch_size}

datasets: # override as needed
  tripunlamb_rare_forget:
    args:
      hf_args:
        path: "SwetieePawsss/TripUNLamb"
        split: ${eval.tripunlamb.forget_split} #_perturbed
      question_key: ${eval.tripunlamb.question_key}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left