# @package eval.tripunlamb.metrics.retain_Q_A_ROUGE
defaults:
  - ../../data/datasets@datasets: tripunlamb_rare_retain
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.tripunlamb.batch_size}
datasets: # override as needed
  tripunlamb_retain_eval: #TOFU_QA_retain_eval:
    args:
      question_key: ${eval.tripunlamb.question_key}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left