# @package eval.popqa
# NOTE: the above line is not a comment, but sets the package for config. See https://hydra.cc/docs/upgrades/0.11_to_1.0/adding_a_package_directive/

defaults: # include all defined metrics files
  - popqa_metrics: # When you import a metric here, its configuration automatically populates the 
  # metric key below, enabled by the @package directive at the top of each configuration file.
    # - forget_quality
    # - forget_Q_A_Prob
    - forget_Q_A_ROUGE
    # - model_utility # populated in the metrics key as metrics.model_utility
    # - privleak
    # - extraction_strength

handler: PopQAEvaluator
output_dir: ${paths.output_dir} # set to default eval directory
metrics: {} # lists a mapping from each evaluation metric to its config 
# populated through the first (@package) line in each metric config
overwrite: false
forget_split: rare_forget10 #popular_forget10 #rare_forget10
# holdout_split: holdout10
retain_logs_path: null
question_key: "question" # Specifies which key to use during forget and retain evaluations (e.g., "question" or "paraphrased_question")
batch_size: 32

# forget_split:     ${forget_split}
# retain_split:     ${retain_split}
# retain_logs_path: ${retain_logs_path}
# question_key: ${question_key}
# batch_size:       32