defaults:
  - _self_
  - model: Llama-3.1-8B-Instruct #Phi-3.5-mini-instruct #gemma-7b-it #Llama-3.1-8B-Instruct #Llama-3.2-3B-Instruct #Llama-3.2-1B-Instruct
  - trainer: finetune
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tripunlamb #tofu
  - hydra: default
  - paths: default
  - experiment: null

mode: train
task_name: ???