defaults:
  - model: Llama-3.1-8B-Instruct #Phi-3.5-mini-instruct #gemma-7b-it #Llama-3.2-1B-Instruct
  - trainer: GradAscent
  - data: unlearn
  - collator: DataCollatorForSupervisedDataset
  - eval: tripunlamb
  - hydra: default
  - paths: default
  - experiment: null
  - _self_

trainer:
  args: 
    remove_unused_columns: False

mode: unlearn
task_name: ???